#define DETECTION_BUFFER_LENGTH         10
#define DETECTION_WINDOW_LENGTH         5
#define DETECTION_END_WINDOW_LENGTH     30

#define GESTURE_BUFFER_LENGTH           200
#define THRESHOLD_ADJ_BUFFER_LENGTH     100

#define READ_PERIOD                     10
#define GESTURE_MIN_TIME_MS             100

#define READING_WINDOW_LENGTH   200
#define ML_DATA_LENGTH 100